include:
  - compose.infrastructure.yml
  - compose.services.yml
  - compose.profiling.yml

services:
  easypay-service:
    image: easypay-service:latest
    hostname: easypay-service
    container_name: easypay-service
    build:
      context: .
      dockerfile: ./easypay-service/src/main/docker/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      SPRING_PROFILES_ACTIVE: default,docker
      OTEL_RESOURCE_ATTRIBUTES: "service.name=easypay-service,deployment.environment=dev,service.namespace=service,service.version=1.0.0,service.instance.id=easypay-service:8080" # (1)
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc # (2)
      OTEL_EXPORTER_OTLP_ENDPOINT: http://opentelemetry-collector:4317 # (3)
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      postgres-easypay:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8080/actuator/health
      interval: 5s
      timeout: 4s
      retries: 10
      start_period: 5s
    entrypoint:
      - java
      - -javaagent:/opentelemetry-javaagent.jar # < Add this line 
      - -javaagent:/opentelemetry-javaagent.jar
      - -Dotel.instrumentation.logback-appender.experimental-log-attributes=true       # < Add this line
      - -Dotel.instrumentation.logback-appender.experimental.capture-mdc-attributes=*  # < Add this line      
      - -Dotel.metric.export.interval=5000 # < Add this line
      - -cp
      - app:app/lib/*
      - com.worldline.easypay.EasypayServiceApplication